using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;

namespace RestApisGen
{
    static class ParameterRecordsFs
    {
        private class ParamInfo
        {
            public string Name;
            public string Type;
            public bool IsOptional;
        }

        public static void Generate(IEnumerable<ApiParent> apis, TextWriter writer)
        {
            writer.Write(@"// This file was automatically generated by CoreTweet.
// Do not modify this file directly.

namespace CoreTweet
open System
open System.Collections.Generic
type long = int64

[<AutoOpen>]
module CoreTweetFSharp =
");
            var ind = new Indent(1);
            foreach (var apiGroup in apis)
            {
                foreach (var endpoint in apiGroup.Endpoints.Where(x => x.Params.Length > 0))
                {
                    writer.WriteLine("{0}type {1}Parameter = {{", ind, apiGroup.Name + endpoint.Name);
                    ind.Inc();
                    var parameters = new List<ParamInfo>();
                    var areAllOptional = endpoint.AnyOneGroups.Any(x => !x.Any());
                    var isEitherRequired = false;
                    if (!areAllOptional && endpoint.AnyOneGroups.Count > 0)
                    {
                        var eithered = Extensions.Combinate(endpoint.AnyOneGroups).ToArray();
                        var prmNames = eithered[0].SelectMany(x => x.Select(y => y.RealName)).ToArray();
                        isEitherRequired = eithered.All(x => x.SelectMany(y => y.Select(z => z.RealName)).SequenceEqual(prmNames));
                    }
                    foreach (var param in endpoint.Params)
                    {
                        var pi = parameters.Find(x => x.Name == param.RealName);
                        if (pi != null)
                        {
                            if (pi.Type != param.Type)
                                pi.Type = "Object";
                        }
                        else
                        {
                            parameters.Add(new ParamInfo()
                            {
                                Name = param.RealName,
                                Type = param.Type,
                                IsOptional = param.Kind == "required"
                                    ? false
                                    : param.Kind == "any one is required"
                                        ? !isEitherRequired
                                        : true
                            });
                        }                        
                    }
                    foreach (var param in parameters)
                    {
                        writer.WriteLine("{0}{1}: {2}", ind, param.Name, param.IsOptional ? (param.Type + " option") : param.Type);
                    }
                    ind.Dec();
                    writer.WriteLine(ind + "}");
                    writer.WriteLine();
                }
            }
        }
    }
}
